---
version: '3.9'

x-base: &base
  volumes:
    - "$HOME/.aws:/root/.aws"
    - "$HOME/.kube:/root/.kube"
    - ".:/app"
  working_dir: /app
  platform: linux/amd64
  environment:
    - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-southeast-2}
    - AWS_PROFILE

services:

  sh:
    <<: *base
    image: ikerry/k8s-toolkit:v1.1.0
    entrypoint: bash
